import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { hasLocale, NextIntlClientProvider} from "next-intl"
import Layout from "@/provider";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const workSans = Work_Sans({
  variable: "--font-work-mono",
  subsets: ["latin"], 
  weight: ["400", "600", "700"]
});

export const metadata: Metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string}>
}>) {
  const {locale} = await params
  if(!hasLocale(routing.locales, locale)){
    notFound()
  }
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body
        className={`${workSans.variable} antialiased`}>
          <NextIntlClientProvider>
            <Layout>
              {children}
            </Layout>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
